---
- hosts: consul_instances
  become: true
  vars:
    consul_enable_local_script_checks: true
    consul_config_custom:
      telemetry:
        prometheus_retention_time: "10m"
        disable_hostname: true
  roles:
    - { role: brianshumate.consul, tags: ['consul'] }
  tasks:
    - name: Register consul metrics service
      consul:
        service_name: consul-metrics
        service_port: 8500
        http: http://localhost:8500/
        interval: 15s
        timeout: 10s
