---
- hosts: all
  become: true
  vars:
    - epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    - epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    - epel_repofile_path: "/etc/yum.repos.d/epel.repo"
    - redhat_packages:
      - vim
      - tmux
      - stress
      - ca-certificates
      - zlib-devel
      - openssl-devel
      - python-pip
      - python-devel
      - sshpass
      - bind-utils
      - jq
    - debian_packages:
      - vim
      - tmux
      - stress
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python-pip
      - python-dev
      - build-essential
      - virtualenv
      - sshpass
      - dnsutils
      - jq
  tasks:
    - name: Install required system packages for RedHat based OS
      block:
        - name: Check if EPEL repo is already configured
          stat: path={{ epel_repofile_path }}
          register: epel_repofile_result
        - name: Install EPEL repo
          yum:
            name: "{{ epel_repo_url }}"
            state: present
          register: result
          when: not epel_repofile_result.stat.exists
        - name: Import EPEL GPG key
          rpm_key:
            key: "{{ epel_repo_gpg_key_url }}"
            state: present
          when: not epel_repofile_result.stat.exists
        - name: Install RedHat packages dependencies
          yum:
            name: "{{ redhat_packages }}"
            state: present
      when: ansible_os_family == 'RedHat'
    - name: Install required system packages for Debian based OS
      block:
        - name: Install Debian packages dependencies
          apt:
            name: "{{ debian_packages }}"
            state: present
            update_cache: true
            force: yes
      when: ansible_os_family == 'Debian'
    - name: Install pip modules for dependencies
      pip:
        name:
          - jsondiff
          - pyyaml
          - python-consul
          - requests
